name: "Secret Scanning Custom Notifications"
description: "A GitHub action that runs on a user specified frequency to retrieve new, closed and dismissed secret scanning alerts since last run. It sends out emails to the security managers."
author: "ps-advanced-security"
inputs:
  frequency:
    required: true
    description: "Defines how often the action should run."
  level:
    required: true
    description: "Defines whether the Action should run on the repo, org or enterprise level."
runs:
  using: "node16"
  main: "dist/index.js"
