
name: "Notification Test" 

on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch: 
  
  
jobs:
  get-alerts:
    name: GetAlerts
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
      repository-projects: write
      
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          
      - name: Call custom secret scanning action
        uses: advanced-security-demo/secret-scanning-custom-notifications@s-samadi/features
        with:
          frequency: ${{ steps.get_frequency.outputs.frequency_in_hours }}
          scope: 'repository'
          new_alerts_filepath: 'created_alerts.json'
          closed_alerts_filepath: 'closed_alerts.json'
          token: ${{ steps.get_workflow_token.outputs.token }}
          
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            created_alerts.json
            closed_alerts.json

      - name: Send an email with the two files
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAILUSER }}
          password: ${{ secrets.EMAILPASS }}
          subject: "New Alerts"
          body: "New Alerts"
          from: ${{ secrets.EMAILUSER }}
          to: ${{ secrets.EMAILUSER }}
          attachments: *.json